<a href="https://colab.research.google.com/github/peremartra/fairness-pruning/blob/main/notebooks/02_Evaluate_MBBQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fairness Pruning Research - MBBQ (EsBBQ) Evaluation
## 02 - Multilingual BBQ Benchmark for Spanish Bias Detection

### Establishing Bias Performance using EsBBQ (MBBQ) for Spanish Bias Mitigation Research
by [Pere Martra](https://github.com/peremartra)

[![GitHub](https://img.shields.io/badge/⭐_Star-OptiPFair-orange?logo=github&logoColor=white)](https://github.com/peremartra/optipfair)
[![PyPI](https://img.shields.io/pypi/v/optipfair?logo=python&logoColor=white&label=v)](https://pypi.org/project/optipfair/)

**Repository:** [github.com/peremartra/fairness-pruning](https://github.com/peremartra/fairness-pruning)

---

**Colab Environment:** GPU L4 or A100

**Models to Evaluate:**
* Llama-3.2-1B (base)
* Llama-3.2-3B (base)
* Salamandra-2B (base)
* Llama-3.1-8B (base)
* Salamandra-7B (base)

**EsBBQ Categories:**
* Age, Disability Status, Gender, LGBTQIA+, Nationality
* Physical Appearance, Race/Ethnicity, Religion, SES, Spanish Region

---

**Note:** This notebook evaluates ONLY base models (no pruning applied) on Spanish bias benchmarks. For English BBQ evaluation, see `02_Evaluate_BBQ.ipynb`.

---

## Evaluation log

| Run | Date | Models | Task | Settings |
|---|---|---|---|---|
| 1 | 2026-02-20/22 (per `results/bias-benchmarks-base/README.md`) | BSC-LT/salamandra-2b, meta-llama/Llama-3.2-1B, meta-llama/Llama-3.2-3B | `esbbq_*` (10 categories) | 0-shot, bfloat16, `batch_size=8` (value hard-coded in `utils.py` until 2026-05-15), lm-eval [fill in]; all 10 tasks in a single `model_evaluation` call |
| 2 | [date] | meta-llama/Llama-3.1-8B | `esbbq_*` (10 categories, full dataset) | 0-shot, bfloat16, `batch_size=16`, one task per call via `run_robust_evaluation` (checkpoint after each task), versions and GPU as printed by the setup cell |
| 3 | [date] | BSC-LT/salamandra-7b | `esbbq_*` (10 categories, full dataset) | same as run 2 |

Notes:
- One model per run: edit `EXPERIMENT_CONFIG` in the configuration cell.
- Raw lm-eval JSON with per-item predictions (`log_samples=True`):
  - Runs 2 and 3: `fair_pruning/checkpoints_mbbq/results/lm_evals/<model>_esbbq_<category>.json`, one task per file.
  - Run 1: `fair_pruning/checkpoints_mbbq/<size>/results/lm_evals/`. It was a single multi-task call, so each per-category file may contain the output of all 10 tasks (check before using them).
- GPU: [fill in].

# 1. Setup & Installation

In [1]:
# Clone the repository (light: no history, only notebooks and custom tasks)
import os, subprocess, sys

REPO_URL = "https://github.com/peremartra/fairness-pruning.git"
REPO_DIR = "fairness-pruning"

if not os.path.exists(REPO_DIR):
    !git clone -q --depth 1 --filter=blob:none --sparse {REPO_URL}
    !cd {REPO_DIR} && git sparse-checkout set notebooks custom_tasks
else:
    print("Repo already cloned. Pulling latest changes...")
    !cd {REPO_DIR} && git pull -q

%cd {REPO_DIR}
print(f"Working directory: {os.getcwd()}")

# Install dependencies from requirements.txt
subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"]
)
print("Dependencies installed.")

# Versions actually in use (for the evaluation log)
from importlib.metadata import version
for pkg in ("torch", "transformers", "lm-eval", "accelerate", "datasets"):
    print(f"{pkg:14s} {version(pkg)}")
print("Python:", sys.version.split()[0])
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (8/8), 40.49 KiB | 40.49 MiB/s, done.
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 70 (delta 45), reused 50 (delta 32), pack-reused 0 (from 0)
Receiving objects: 100% (70/70), 6.46 MiB | 24.06 MiB/s, done.
Resolving deltas: 100% (45/45), done.
Updating files: 100% (79/79), done.
/content/fairness-pruning
Working directory: /content/fairness-pruning
Dependencies installed.
torch          2.10.0
transformers   4.57.3
lm-eval        0.4.9.2
accelerate     1.13.0
datasets       4.0.0
Python: 3.13.16
NVIDIA L4, 23034 MiB

In [2]:
# Mount Google Drive for checkpoint persistence
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# SIMPLE INSTALLATION OF EsBBQ (files already cleaned in the repo)
import os
import shutil
import lm_eval

print(f"{'='*70}")
print("📦 INSTALLING EsBBQ TASKS")
print(f"{'='*70}")

# 1. Locate directories
lib_path = os.path.dirname(lm_eval.__file__)
target_dir = os.path.join(lib_path, "tasks", "esbbq")

# 2. Clean and recreate directory
if os.path.exists(target_dir):
    shutil.rmtree(target_dir)
os.makedirs(target_dir, exist_ok=True)
print(f"📍 TASKS DIRECTORY: {target_dir}\n")

# 3. Copy all YAMLs and Python (.py) files
files_to_copy = [f for f in os.listdir('custom_tasks/esbbq') if f.endswith('.yaml') or f.endswith('.py')]

for file_name in files_to_copy:
    src = os.path.join('custom_tasks/esbbq', file_name)
    dst = os.path.join(target_dir, file_name)
    shutil.copy(src, dst)
    print(f"   ✅ {file_name}")

print(f"\n🚀 OK! {len(files_to_copy)} EsBBQ files installed.")

======================================================================
📦 INSTALLING EsBBQ TASKS
======================================================================
📍 TASKS DIRECTORY: /usr/local/lib/python3.13/dist-packages/lm_eval/tasks/esbbq

   ✅ esbbq_disabilitystatus.yaml
   ✅ esbbq_raceethnicity.yaml
   ✅ esbbq_physicalappearance.yaml
   ✅ esbbq_spanishregion.yaml
   ✅ esbbq_nationality.yaml
   ✅ esbbq_religion.yaml
   ✅ esbbq_ses.yaml
   ✅ esbbq_utils.py
   ✅ esbbq_gender.yaml
   ✅ esbbq_age.yaml
   ✅ esbbq_lgbtqia.yaml

🚀 OK! 11 EsBBQ files installed.

# 2. Configuration & Evaluation Plan (MBBQ/EsBBQ)

Configure paths, select EsBBQ tasks, and list the models we will evaluate.

In [4]:
import torch
import json
import pandas as pd
from datetime import datetime
from pathlib import Path
import logging
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from IPython.display import display
from utils import (
    #EXPERIMENT_CONFIG,
    run_robust_evaluation,
    load_or_create_model,
    clear_gpu_cache,
    format_results_table,
    get_model_stats,
 )

# Paths (Drive recommended in Colab)
CHECKPOINT_BASE_DIR = "/content/drive/MyDrive/fair_pruning/checkpoints_mbbq"
RESULTS_DIR = "/content/drive/MyDrive/fair_pruning/results"
Path(CHECKPOINT_BASE_DIR).mkdir(parents=True, exist_ok=True)
Path(RESULTS_DIR).mkdir(parents=True, exist_ok=True)

# EsBBQ (MBBQ) task list - all categories in one group (0-shot)
# Using task group name that encompasses all EsBBQ subtasks
MBBQ_TASKS = [
    {"name": "esbbq_age", "num_fewshot": 0},
    {"name": "esbbq_disabilitystatus", "num_fewshot": 0},
    {"name": "esbbq_gender", "num_fewshot": 0},
    {"name": "esbbq_lgbtqia", "num_fewshot": 0},
    {"name": "esbbq_nationality", "num_fewshot": 0},
    {"name": "esbbq_physicalappearance", "num_fewshot": 0},
    {"name": "esbbq_raceethnicity", "num_fewshot": 0},
    {"name": "esbbq_religion", "num_fewshot": 0},
    {"name": "esbbq_ses", "num_fewshot": 0},
    {"name": "esbbq_spanishregion", "num_fewshot": 0}
]

# Models to evaluate in this run (one model per run, see the evaluation log above)
EXPERIMENT_CONFIG = [
    {
        "base_model": "meta-llama/Llama-3.1-8B",
    },
]
unique_models = list(dict.fromkeys([cfg["base_model"] for cfg in EXPERIMENT_CONFIG]))

logging.getLogger("lm_eval").setLevel(logging.INFO)

print(f"{'='*70}")
print("📊 EVALUATION PLAN: MBBQ (EsBBQ) - Spanish Bias Benchmark")
print(f"{'='*70}")
print(f"Checkpoints: {CHECKPOINT_BASE_DIR}")
print(f"Results: {RESULTS_DIR}")
print(f"Tasks: {[task['name'] for task in MBBQ_TASKS]}")
print("Limit per dataset: None (full dataset) | batch_size=16")
print("Models:")
for m in unique_models:
    print(f" - {m}")
print(f"{'='*70}\n")

======================================================================
📊 EVALUATION PLAN: MBBQ (EsBBQ) - Spanish Bias Benchmark
======================================================================
Checkpoints: /content/drive/MyDrive/fair_pruning/checkpoints_mbbq
Results: /content/drive/MyDrive/fair_pruning/results
Tasks: ['esbbq_age', 'esbbq_disabilitystatus', 'esbbq_gender', 'esbbq_lgbtqia', 'esbbq_nationality', 'esbbq_physicalappearance', 'esbbq_raceethnicity', 'esbbq_religion', 'esbbq_ses', 'esbbq_spanishregion']
Limit per dataset: None (full dataset) | batch_size=16
Models:
 - meta-llama/Llama-3.1-8B
======================================================================

# 3. Helper Functions

Utility functions for automatic checkpoint path generation and model size detection.

In [5]:
import re
import os

def get_model_size(model_name: str) -> str:
    """Extract model size identifier from HuggingFace model name.

    Examples:
        "meta-llama/Llama-3.2-1B" → "1b"
        "meta-llama/Llama-3.2-3B-Instruct" → "3b_instruct"
        "BSC-LT/salamandra-2b" → "2b"
    """
    match = re.search(r'(\d+\.?\d*)[Bb]', model_name)
    if not match:
        return "unknown"

    size = match.group(1).replace('.', '_') + "b"
    if "instruct" in model_name.lower():
        size += "_instruct"

    return size.lower()

def get_checkpoint_path(model_name: str, base_dir: str) -> str:
    """Generate checkpoint path with size-based subdirectory.

    Args:
        model_name: Full HuggingFace model identifier
        base_dir: Base directory for checkpoints

    Returns:
        Full path to checkpoint file
    """
    model_size = get_model_size(model_name)
    safe_name = model_name.replace('/', '_').replace('-', '_').lower()
    checkpoint_dir = os.path.join(base_dir, model_size)
    os.makedirs(checkpoint_dir, exist_ok=True)
    return os.path.join(checkpoint_dir, f"{safe_name}.json")

# Test with EXPERIMENT_CONFIG
print("Testing helper functions with EXPERIMENT_CONFIG:")
print("-" * 70)
for cfg in EXPERIMENT_CONFIG:
    model_id = cfg['base_model']
    size = get_model_size(model_id)
    print(f"{model_id:<50} → {size}")
print("-" * 70)

Testing helper functions with EXPERIMENT_CONFIG:
----------------------------------------------------------------------
meta-llama/Llama-3.1-8B                            → 8b
----------------------------------------------------------------------

# 4. Run MBBQ Evaluation

Evaluate each base model on EsBBQ tasks with checkpoint/resume and raw result saving.

In [6]:
print(f"\n{'='*70}")
print("🚀 STARTING MBBQ (EsBBQ) EVALUATION (Hugging Face Native Loading)")
print(f"{'='*70}\n")

all_model_results = {}

for idx, model_id in enumerate(unique_models, 1):
    print(f"\n{'='*70}")
    print(f"📊 MODEL {idx}/{len(unique_models)}: {model_id}")
    print(f"{'='*70}\n")
    try:
        # Generar ruta de checkpoint
        checkpoint_path = get_checkpoint_path(model_id, CHECKPOINT_BASE_DIR)

        # --- CARGA DIRECTA CON HUGGING FACE ---
        print(f"📥 Loading directly from Hugging Face Hub...")
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto"
        )

        tokenizer = AutoTokenizer.from_pretrained(model_id)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        print("✅ Model loaded successfully (Native HF)")

        # Mostrar estadísticas
        stats = get_model_stats(model)
        print(f"📈 Params: {stats['total_parameters']:,} | Size: {stats['size_gb']:.2f} GB")
        print(f"📁 Checkpoint: {checkpoint_path}\n")

        # --- Run evaluation: checkpoint saved after each task (resume on re-run);
        # raw per-item lm-eval JSON per task in <CHECKPOINT_BASE_DIR>/results/lm_evals/ ---
        results = run_robust_evaluation(
            model=model,
            tokenizer=tokenizer,
            tasks=MBBQ_TASKS,
            checkpoint_path=checkpoint_path,
            model_name=model_id,
            batch_size=16
        )
        # -----------------------------------------------

        all_model_results[model_id] = results
        print(f"\n✅ Completed: {model_id}")
        print("Results Preview:")
        print(format_results_table(results))

    except Exception as e:
        print(f"\n❌ ERROR evaluating {model_id}: {e}")
        import traceback
        traceback.print_exc()
        if 'model' in locals(): del model
        if 'tokenizer' in locals(): del tokenizer
        clear_gpu_cache()
        continue

    # Limpieza de memoria
    del model
    del tokenizer
    clear_gpu_cache()

print(f"\n{'='*70}")
print(f"✅ MBBQ EVALUATION COMPLETE: {len(all_model_results)}/{len(unique_models)} models")
print(f"{'='*70}\n")

======================================================================
🚀 STARTING MBBQ (EsBBQ) EVALUATION (Hugging Face Native Loading)
======================================================================


======================================================================
📊 MODEL 1/1: meta-llama/Llama-3.1-8B
======================================================================

📥 Loading directly from Hugging Face Hub...

config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

✅ Model loaded successfully (Native HF)
📈 Params: 8,030,261,248 | Size: 14.96 GB
📁 Checkpoint: /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/8b/meta_llama_llama_3.1_8b.json

📂 Found existing checkpoint: /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/8b/meta_llama_llama_3.1_8b.json
✅ Loaded checkpoint. Completed: 8/10 tasks
   Pending: ['esbbq_ses', 'esbbq_spanishregion']

======================================================================
🚀 Starting evaluation: 2 tasks remaining
======================================================================


[1/2] Evaluating: esbbq_ses
──────────────────────────────────────────────────────────────────────

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.
WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration
INFO:lm_eval.evaluator:Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234
INFO:lm_eval.evaluator:Using pre-initialized model

======================================================================
Starting lm-eval on model 'meta-llama/Llama-3.1-8B'
Tasks: ['esbbq_ses'] (full dataset)
Few-shot config: {'esbbq_ses': 0}
======================================================================

README.md: 0.00B [00:00, ?B/s]

SES/test-00000-of-00001.parquet:   0%|          | 0.00/147k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/4204 [00:00<?, ? examples/s]

INFO:lm_eval.tasks:Selected tasks:
INFO:lm_eval.tasks:Task: esbbq_ses (esbbq/esbbq_ses.yaml)
INFO:lm_eval.evaluator:num_fewshot has been set to 0 for esbbq_ses in its config. Manual configuration will be ignored.
INFO:lm_eval.api.task:Building contexts for esbbq_ses on rank 0...
100%|██████████| 4204/4204 [00:03<00:00, 1346.66it/s]
INFO:lm_eval.evaluator:Running loglikelihood requests
Running loglikelihood requests: 100%|██████████| 46244/46244 [23:28<00:00, 32.83it/s]

💾 Saving raw results to: /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/results/lm_evals

WARNING:lm_eval.models.huggingface:`pretrained` model kwarg is not of type `str`. Many other model arguments may be ignored. Please do not launch via accelerate or use `parallelize=True` if passing an existing model this way.
WARNING:lm_eval.models.huggingface:Passed an already-initialized model through `pretrained`, assuming single-process call to evaluate() or custom distributed integration
INFO:lm_eval.evaluator:Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234
INFO:lm_eval.evaluator:Using pre-initialized model

   ✅ Saved: meta_llama_llama_3.1_8b_esbbq_ses.json
✅ esbbq_ses completed and saved to checkpoint
   Results: {'alias': 'esbbq_ses', 'acc': '0.5985', 'acc_stderr': '0.0076', 'acc_norm': '0.5985', 'acc_norm_stderr': '0.0076', 'acc_ambig': '0.2181', 'acc_ambig_stderr': 'N/A', 'acc_disambig': '0.7843', 'acc_disambig_stderr': 'N/A', 'bias_score_ambig': '0.0587', 'bias_score_ambig_stderr': 'N/A', 'bias_score_disambig': '-0.0639', 'bias_score_disambig_stderr': 'N/A'}

[2/2] Evaluating: esbbq_spanishregion
──────────────────────────────────────────────────────────────────────

======================================================================
Starting lm-eval on model 'meta-llama/Llama-3.1-8B'
Tasks: ['esbbq_spanishregion'] (full dataset)
Few-shot config: {'esbbq_spanishregion': 0}
======================================================================

SpanishRegion/test-00000-of-00001.parque(…):   0%|          | 0.00/43.7k [00:00<?, ?B/s]

Generating test split:   0%|          | 0/988 [00:00<?, ? examples/s]

INFO:lm_eval.tasks:Selected tasks:
INFO:lm_eval.tasks:Task: esbbq_spanishregion (esbbq/esbbq_spanishregion.yaml)
INFO:lm_eval.evaluator:num_fewshot has been set to 0 for esbbq_spanishregion in its config. Manual configuration will be ignored.
INFO:lm_eval.api.task:Building contexts for esbbq_spanishregion on rank 0...
100%|██████████| 988/988 [00:00<00:00, 1452.51it/s]
INFO:lm_eval.evaluator:Running loglikelihood requests
Running loglikelihood requests: 100%|██████████| 10868/10868 [05:09<00:00, 35.08it/s]

💾 Saving raw results to: /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/results/lm_evals
   ✅ Saved: meta_llama_llama_3.1_8b_esbbq_spanishregion.json
✅ esbbq_spanishregion completed and saved to checkpoint
   Results: {'alias': 'esbbq_spanishregion', 'acc': '0.6154', 'acc_stderr': '0.0155', 'acc_norm': '0.6154', 'acc_norm_stderr': '0.0155', 'acc_ambig': '0.0988', 'acc_ambig_stderr': 'N/A', 'acc_disambig': '0.8675', 'acc_disambig_stderr': 'N/A', 'bias_score_ambig': '0.0123', 'bias_score_ambig_stderr': 'N/A', 'bias_score_disambig': '0.0241', 'bias_score_disambig_stderr': 'N/A'}

======================================================================
🎉 ALL TASKS COMPLETED!
======================================================================


✅ Completed: meta-llama/Llama-3.1-8B
Results Preview:
                    task                    alias    acc acc_stderr acc_norm acc_norm_stderr acc_ambig acc_ambig_stderr acc_disambig acc_disambig_stderr bias_score_ambig bias_score_ambig_stderr bias_score_disambig bias_score_disambig_stderr
               esbbq_age                esbbq_age 0.4813     0.0078   0.4813          0.0078    0.0666              N/A       0.6744                 N/A           0.0619                     N/A             -0.0144                        N/A
  esbbq_disabilitystatus   esbbq_disabilitystatus 0.5696     0.0093   0.5696          0.0093    0.1218              N/A       0.7878                 N/A           0.0420                     N/A              0.0588                        N/A
            esbbq_gender             esbbq_gender 0.5072     0.0072   0.5072          0.0072    0.0020              N/A       0.7356                 N/A           0.1031                     N/A              0.0084                        N/A
           esbbq_lgbtqia            esbbq_lgbtqia 0.5800     0.0110   0.5800          0.0110    0.2465              N/A       0.7149                 N/A           0.0312                     N/A             -0.0140                        N/A
       esbbq_nationality        esbbq_nationality 0.5437     0.0222   0.5437          0.0222    0.0893              N/A       0.7708                 N/A           0.1726                     N/A             -0.0060                        N/A
esbbq_physicalappearance esbbq_physicalappearance 0.5862     0.0083   0.5862          0.0083    0.3214              N/A       0.7185                 N/A           0.1820                     N/A              0.0612                        N/A
     esbbq_raceethnicity      esbbq_raceethnicity 0.5043     0.0082   0.5043          0.0082    0.0562              N/A       0.7255                 N/A           0.0448                     N/A              0.0217                        N/A
          esbbq_religion           esbbq_religion 0.6127     0.0192   0.6127          0.0192    0.1944              N/A       0.8218                 N/A          -0.0648                     N/A             -0.0602                        N/A
               esbbq_ses                esbbq_ses 0.5985     0.0076   0.5985          0.0076    0.2181              N/A       0.7843                 N/A           0.0587                     N/A             -0.0639                        N/A
     esbbq_spanishregion      esbbq_spanishregion 0.6154     0.0155   0.6154          0.0155    0.0988              N/A       0.8675                 N/A           0.0123                     N/A              0.0241                        N/A
🧹 GPU memory cleared. Available: 23.66 GB

======================================================================
✅ MBBQ EVALUATION COMPLETE: 1/1 models
======================================================================

# 5. Consolidate MBBQ Results

Load checkpoint files, flatten metrics, and export combined MBBQ results in CSV/JSON format.

In [7]:
import glob

def flatten_metrics(metrics, prefix=''):
    """Recursively flatten nested metric dictionaries."""
    flat = {}
    for k, v in metrics.items():
        if isinstance(v, dict):
            flat.update(flatten_metrics(v, prefix=f"{prefix}{k}_"))
        else:
            flat[f"{prefix}{k}"] = v
    return flat

print(f"{'='*70}")
print(" CONSOLIDATING MBBQ RESULTS")
print(f"{'='*70}\n")

checkpoint_files = glob.glob(f"{CHECKPOINT_BASE_DIR}/**/*.json", recursive=True)
print(f"Total checkpoint JSONs found: {len(checkpoint_files)}")

consolidated_data = []

for json_path in sorted(checkpoint_files):
    # Skip raw lm-eval dumps (only process model checkpoints)
    if "lm_evals" in json_path:
        continue

    try:
        with open(json_path, "r") as f:
            data = json.load(f)

        metadata = data.get("metadata", {})
        model_name = metadata.get("model_name", "Unknown")

        # Extract model size
        model_size = get_model_size(model_name)

        results = data.get("results", {})
        if not results:
            continue

        for task_name, metrics in results.items():
            row = {
                "model": model_name,
                "model_size": model_size,
                "task": task_name,
            }
            row.update(flatten_metrics(metrics))
            if "accuracy" not in row and "acc" in row:
                row["accuracy"] = row["acc"]
            consolidated_data.append(row)

    except Exception as e:
        print(f"   ⚠️ Error reading {json_path}: {e}")

if consolidated_data:
    df = pd.DataFrame(consolidated_data)
    df = df.sort_values(by=["model", "task"]).reset_index(drop=True)

    print(f"\n📊 Consolidated {len(df)} task results from {df['model'].nunique()} models")
    display(df.head(10))

    # Save timestamped and latest versions
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_path = f"{RESULTS_DIR}/base_models_mbbq_results_{timestamp}.csv"
    latest_csv = f"{RESULTS_DIR}/base_models_mbbq_results_latest.csv"
    json_path = f"{RESULTS_DIR}/base_models_mbbq_results_{timestamp}.json"

    df.to_csv(csv_path, index=False)
    df.to_csv(latest_csv, index=False)
    df.to_json(json_path, orient="records", indent=2)

    print("\n💾 MBBQ results saved:")
    print(f"   {csv_path}")
    print(f"   {latest_csv}")
    print(f"   {json_path}")
else:
    print("⚠️ No MBBQ results found to consolidate.")

======================================================================
 CONSOLIDATING MBBQ RESULTS
======================================================================

Total checkpoint JSONs found: 44

📊 Consolidated 40 task results from 4 models

,model,model_size,task,alias,acc,acc_stderr,acc_norm,acc_norm_stderr,acc_ambig,acc_ambig_stderr,acc_disambig,acc_disambig_stderr,bias_score_ambig,bias_score_ambig_stderr,bias_score_disambig,bias_score_disambig_stderr,accuracy
0,BSC-LT/salamandra-2b,2b,esbbq_age,esbbq_age,0.3614,0.0075,0.3614,0.0075,0.0759,N/A,0.4942,N/A,0.0093,N/A,0.0605,N/A,0.3614
1,BSC-LT/salamandra-2b,2b,esbbq_disabilitystatus,esbbq_disabilitystatus,0.4520,0.0094,0.4520,0.0094,0.3308,N/A,0.5110,N/A,0.0248,N/A,0.0200,N/A,0.4520
2,BSC-LT/salamandra-2b,2b,esbbq_gender,esbbq_gender,0.3609,0.0069,0.3609,0.0069,0.0033,N/A,0.5225,N/A,-0.0007,N/A,0.0030,N/A,0.3609
3,BSC-LT/salamandra-2b,2b,esbbq_lgbtqia,esbbq_lgbtqia,0.4220,0.0110,0.4220,0.0110,0.3455,N/A,0.4529,N/A,0.0087,N/A,0.0154,N/A,0.4220
4,BSC-LT/salamandra-2b,2b,esbbq_nationality,esbbq_nationality,0.4167,0.0220,0.4167,0.0220,0.1726,N/A,0.5387,N/A,0.0417,N/A,-0.0060,N/A,0.4167
5,BSC-LT/salamandra-2b,2b,esbbq_physicalappearance,esbbq_physicalappearance,0.5346,0.0084,0.5346,0.0084,0.6148,N/A,0.4945,N/A,0.0077,N/A,0.0808,N/A,0.5346
6,BSC-LT/salamandra-2b,2b,esbbq_raceethnicity,esbbq_raceethnicity,0.3689,0.0079,0.3689,0.0079,0.0871,N/A,0.5080,N/A,0.0269,N/A,0.0000,N/A,0.3689
7,BSC-LT/salamandra-2b,2b,esbbq_religion,esbbq_religion,0.4414,0.0195,0.4414,0.0195,0.3009,N/A,0.5116,N/A,-0.0972,N/A,-0.0694,N/A,0.4414
8,BSC-LT/salamandra-2b,2b,esbbq_ses,esbbq_ses,0.4436,0.0077,0.4436,0.0077,0.3855,N/A,0.4720,N/A,0.0435,N/A,0.0504,N/A,0.4436
9,BSC-LT/salamandra-2b,2b,esbbq_spanishregion,esbbq_spanishregion,0.3968,0.0156,0.3968,0.0156,0.1944,N/A,0.4955,N/A,0.0154,N/A,-0.0090,N/A,0.3968

💾 MBBQ results saved:
   /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_20261028_141528.csv
   /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_latest.csv
   /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_20261028_141528.json

# 6. Summary Analysis

Quick per-model accuracy summary for MBBQ and file inventory.

In [8]:
# Generate summary statistics
summary_df = None
if 'df' in locals() and not df.empty:
    summaries = []
    for model_name, model_df in df.groupby('model'):
        acc_series = pd.to_numeric(model_df.get('acc', model_df.get('accuracy')), errors='coerce').dropna()
        summaries.append({
            "model": model_name,
            "model_size": model_df.get('model_size', pd.Series(['unknown'])).iloc[0],
            "avg_accuracy": acc_series.mean() if len(acc_series) else None,
            "tasks_completed": len(model_df),
            "categories_evaluated": len(model_df['task'].unique())
        })

    summary_df = pd.DataFrame(summaries)
    summary_df = summary_df.sort_values("model").reset_index(drop=True)

    print(f"{'='*70}")
    print("📈 MBBQ SUMMARY")
    print(f"{'='*70}")
    print(summary_df.to_string(index=False, float_format="%.4f"))

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    summary_csv = f"{RESULTS_DIR}/base_models_mbbq_summary_{timestamp}.csv"
    summary_df.to_csv(summary_csv, index=False)
    print(f"\n💾 Summary saved: {summary_csv}\n")
else:
    print("No consolidated data available for summary.")

# List all generated files
print(f"{'='*70}")
print("📁 GENERATED FILES")
print(f"{'='*70}")

if 'csv_path' in locals() and os.path.exists(csv_path):
    print(f"  ✅ {csv_path}")
if 'latest_csv' in locals() and os.path.exists(latest_csv):
    print(f"  ✅ {latest_csv}")
if 'json_path' in locals() and os.path.exists(json_path):
    print(f"  ✅ {json_path}")
if 'summary_csv' in locals() and os.path.exists(summary_csv):
    print(f"  ✅ {summary_csv}")

print("\nCheckpoints (first 10):")
if 'checkpoint_files' in locals():
    model_checkpoints = [f for f in sorted(checkpoint_files) if "lm_evals" not in f]
    for f in model_checkpoints[:10]:
        print(f"  ✅ {f}")
    if len(model_checkpoints) > 10:
        print(f"  ... and {len(model_checkpoints) - 10} more")

print("\nRaw LM-Eval dumps (first 10):")
if 'checkpoint_files' in locals():
    raw_dumps = [f for f in sorted(checkpoint_files) if "lm_evals" in f]
    for f in raw_dumps[:10]:
        print(f"  ✅ {f}")
    if len(raw_dumps) > 10:
        print(f"  ... and {len(raw_dumps) - 10} more")

print(f"{'='*70}")

======================================================================
📈 MBBQ SUMMARY
======================================================================
                  model model_size  avg_accuracy  tasks_completed  categories_evaluated
   BSC-LT/salamandra-2b         2b        0.4198               10                    10
meta-llama/Llama-3.1-8B         8b        0.5599               10                    10
meta-llama/Llama-3.2-1B         1b        0.4252               10                    10
meta-llama/Llama-3.2-3B         3b        0.5322               10                    10

💾 Summary saved: /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_summary_20261028_141529.csv

======================================================================
📁 GENERATED FILES
======================================================================
  ✅ /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_20261028_141528.csv
  ✅ /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_latest.csv
  ✅ /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_results_20261028_141528.json
  ✅ /content/drive/MyDrive/fair_pruning/results/base_models_mbbq_summary_20261028_141529.csv

Checkpoints (first 10):
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/meta_llama_llama_3.2_1b.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/2b/bsc_lt_salamandra_2b.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/3b/meta_llama_llama_3.2_3b.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/8b/meta_llama_llama_3.1_8b.json

Raw LM-Eval dumps (first 10):
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_age.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_disabilitystatus.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_gender.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_lgbtqia.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_nationality.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_physicalappearance.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_raceethnicity.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_religion.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_ses.json
  ✅ /content/drive/MyDrive/fair_pruning/checkpoints_mbbq/1b/results/lm_evals/meta_llama_llama_3.2_1b_esbbq_spanishregion.json
  ... and 30 more
======================================================================

# 7. Bias Analysis by Category

Analyze bias metrics across EsBBQ categories for each model.

In [9]:
import pandas as pd
import numpy as np
from datetime import datetime

if 'df' in locals() and not df.empty:
    print(f"{'='*70}")
    print("📊 BIAS ANALYSIS BY CATEGORY")
    print(f"{'='*70}\n")

    # --- CORRECCIÓN CRÍTICA ---
    # 1. Unificar nombres: Si existe 'acc' (BBQ) pero no 'accuracy', úsalo.
    # 2. Convertir a NÚMEROS: Forzamos la conversión de texto a float.
    target_col = 'acc' if 'acc' in df.columns else 'accuracy'

    # Creamos/Sobreescribimos la columna 'accuracy' asegurando que sea numérica
    # errors='coerce' transformará cualquier valor no numérico en NaN (Not a Number) para no romper el código
    df['accuracy'] = pd.to_numeric(df[target_col], errors='coerce')
    # ---------------------------

    # Extract category from task name (e.g., esbbq_age -> age)
    df['category'] = df['task'].astype(str).str.replace('esbbq_', '')

    # Pivot table: models as rows, categories as columns
    # Ahora que 'accuracy' es float, aggfunc='mean' funcionará correctamente
    if 'accuracy' in df.columns:
        pivot_df = df.pivot_table(
            index='model',
            columns='category',
            values='accuracy',
            aggfunc='mean'
        )

        print("\nAccuracy by Category:")
        display(pivot_df)

        # Save category breakdown
        if 'RESULTS_DIR' in locals():
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            category_csv = f"{RESULTS_DIR}/mbbq_category_breakdown_{timestamp}.csv"
            pivot_df.to_csv(category_csv)
            print(f"\n💾 Category breakdown saved: {category_csv}")
    else:
        print("⚠️ Column 'accuracy' not found. Available columns:", df.columns.tolist())

    # Show bias score distribution if available
    bias_cols = [col for col in df.columns if 'bias' in col.lower()]
    if bias_cols:
        print("\n📊 Available bias metrics:")
        for col in bias_cols:
            print(f"   - {col}")
else:
    print("No data available for category analysis.")

======================================================================
📊 BIAS ANALYSIS BY CATEGORY
======================================================================


Accuracy by Category:

category,age,disabilitystatus,gender,lgbtqia,nationality,physicalappearance,raceethnicity,religion,ses,spanishregion
model,,,,,,,,,,
BSC-LT/salamandra-2b,0.3614,0.4520,0.3609,0.422,0.4167,0.5346,0.3689,0.4414,0.4436,0.3968
meta-llama/Llama-3.1-8B,0.4813,0.5696,0.5072,0.580,0.5437,0.5862,0.5043,0.6127,0.5985,0.6154
meta-llama/Llama-3.2-1B,0.3387,0.4530,0.3876,0.454,0.4306,0.4858,0.3652,0.4552,0.4346,0.4474
meta-llama/Llama-3.2-3B,0.4400,0.5600,0.4729,0.533,0.5575,0.6040,0.5008,0.5077,0.5592,0.5870

💾 Category breakdown saved: /content/drive/MyDrive/fair_pruning/results/mbbq_category_breakdown_20261028_141529.csv

📊 Available bias metrics:
   - bias_score_ambig
   - bias_score_ambig_stderr
   - bias_score_disambig
   - bias_score_disambig_stderr